### ISSUE TITLE
Remove label prop from Button

### ISSUE THREAD

**Issue by vellip** [Covexit/covexit#26]
We now have children and label props for the same thing. We should just remove the label prop and use children everywhere. Looks nicer too.

**Comment by akolliy1** [comment]
Well, cleaning up label props doesn't sound like a bad idea. But I think most of the time we might want to create a simple button component that has just only text. For this reason, I'll suggest to leave it.

**Comment by vellip** [comment]
It'd be closer to a native button tag  (`<button>label</button>`) that way, that's why I'd prefer it. Plus, as it is now, under the hood label and children do the same thing.
