### ISSUE TITLE
stuck at Waiting for email verification while running on localhost

### ISSUE THREAD

**Issue by soomro30** [Covexit/covexit#79]
While registering the account, the screen is stuck at waiting for email verification on localhost. I never recieve any email. How to bypass this and create a shop and add products

![Screen Shot 2020-04-26 at 9 54 31 PM](https://user-images.githubusercontent.com/1238737/80315467-c980d180-8808-11ea-94ab-edc53fbfc110.png)

**Comment by vellip** [comment]
On localhost the email is output in the console

**Comment by soomro30** [comment]
Could you please help me fix this issue. I cannot find it in the console. I am attaching the console logs image
![Screen Shot 2020-04-26 at 10 26 44 PM](https://user-images.githubusercontent.com/1238737/80316136-22526900-880d-11ea-9480-6871d6f82091.png)

**Comment by vellip** [comment]
It will be printed out at the time when you had registered your user first. You can only clear your localStorage and register again for now

**Comment by soomro30** [comment]
@vellip Thanks. It only appears once you register.
